apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service-deployment
  labels:
    app: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis-service
          image: redis-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083

