apiVersion: v1
kind: Service
metadata:
  name: redis-service-app
spec:
  type: NodePort
  selector:
    app: redis-service
  ports:
    - name: redis-service
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31400